//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estreya.BlishHUD.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Estreya.BlishHUD.Shared.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding Colors to ColorPicker....
        /// </summary>
        internal static string BaseSettingsView_AddingColorsToColorPicker {
            get {
                return ResourceManager.GetString("BaseSettingsView_AddingColorsToColorPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading ColorPicker....
        /// </summary>
        internal static string BaseSettingsView_LoadingColorPicker {
            get {
                return ResourceManager.GetString("BaseSettingsView_LoadingColorPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Colors....
        /// </summary>
        internal static string BaseSettingsView_LoadingColors {
            get {
                return ResourceManager.GetString("BaseSettingsView_LoadingColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the background color..
        /// </summary>
        internal static string Setting_BackgroundColor_Description {
            get {
                return ResourceManager.GetString("Setting_BackgroundColor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Color.
        /// </summary>
        internal static string Setting_BackgroundColor_Name {
            get {
                return ResourceManager.GetString("Setting_BackgroundColor_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the opacity of the background..
        /// </summary>
        internal static string Setting_BackgroundColorOpacity_Description {
            get {
                return ResourceManager.GetString("Setting_BackgroundColorOpacity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Color Opacity.
        /// </summary>
        internal static string Setting_BackgroundColorOpacity_Name {
            get {
                return ResourceManager.GetString("Setting_BackgroundColorOpacity_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the module should be build from the top or the bottom..
        /// </summary>
        internal static string Setting_BuildDirection_Description {
            get {
                return ResourceManager.GetString("Setting_BuildDirection_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Direction.
        /// </summary>
        internal static string Setting_BuildDirection_Name {
            get {
                return ResourceManager.GetString("Setting_BuildDirection_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the module should be running in debug mode..
        /// </summary>
        internal static string Setting_DebugEnabled_Description {
            get {
                return ResourceManager.GetString("Setting_DebugEnabled_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug Enabled.
        /// </summary>
        internal static string Setting_DebugEnabled_Name {
            get {
                return ResourceManager.GetString("Setting_DebugEnabled_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the font size for the module..
        /// </summary>
        internal static string Setting_FontSize_Description {
            get {
                return ResourceManager.GetString("Setting_FontSize_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size.
        /// </summary>
        internal static string Setting_FontSize_Name {
            get {
                return ResourceManager.GetString("Setting_FontSize_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the module should be displayed..
        /// </summary>
        internal static string Setting_GlobalEnabled_Description {
            get {
                return ResourceManager.GetString("Setting_GlobalEnabled_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Enabled.
        /// </summary>
        internal static string Setting_GlobalEnabled_Name {
            get {
                return ResourceManager.GetString("Setting_GlobalEnabled_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The keybinding which will toggle the module..
        /// </summary>
        internal static string Setting_GlobalEnabledHotkey_Description {
            get {
                return ResourceManager.GetString("Setting_GlobalEnabledHotkey_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Hotkey.
        /// </summary>
        internal static string Setting_GlobalEnabledHotkey_Name {
            get {
                return ResourceManager.GetString("Setting_GlobalEnabledHotkey_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether module should hide when the player is in combat..
        /// </summary>
        internal static string Setting_HideInCombat_Description {
            get {
                return ResourceManager.GetString("Setting_HideInCombat_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide in Combat.
        /// </summary>
        internal static string Setting_HideInCombat_Name {
            get {
                return ResourceManager.GetString("Setting_HideInCombat_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the module should hide when the map is open..
        /// </summary>
        internal static string Setting_HideOnMap_Description {
            get {
                return ResourceManager.GetString("Setting_HideOnMap_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide on open Map.
        /// </summary>
        internal static string Setting_HideOnMap_Name {
            get {
                return ResourceManager.GetString("Setting_HideOnMap_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the module should hide when cutscenes are played..
        /// </summary>
        internal static string Setting_HideOnMissingMumbleTicks_Description {
            get {
                return ResourceManager.GetString("Setting_HideOnMissingMumbleTicks_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide on Cutscenes.
        /// </summary>
        internal static string Setting_HideOnMissingMumbleTicks_Name {
            get {
                return ResourceManager.GetString("Setting_HideOnMissingMumbleTicks_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where the module should be displayed on the X axis..
        /// </summary>
        internal static string Setting_LocationX_Description {
            get {
                return ResourceManager.GetString("Setting_LocationX_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location X.
        /// </summary>
        internal static string Setting_LocationX_Name {
            get {
                return ResourceManager.GetString("Setting_LocationX_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where the module should be displayed on the Y axis..
        /// </summary>
        internal static string Setting_LocationY_Description {
            get {
                return ResourceManager.GetString("Setting_LocationY_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Y.
        /// </summary>
        internal static string Setting_LocationY_Name {
            get {
                return ResourceManager.GetString("Setting_LocationY_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the opacity of the module..
        /// </summary>
        internal static string Setting_Opacity_Description {
            get {
                return ResourceManager.GetString("Setting_Opacity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity.
        /// </summary>
        internal static string Setting_Opacity_Name {
            get {
                return ResourceManager.GetString("Setting_Opacity_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the module should add it&apos;s own corner icon to access settings..
        /// </summary>
        internal static string Setting_RegisterCornerIcon_Description {
            get {
                return ResourceManager.GetString("Setting_RegisterCornerIcon_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Corner Icon.
        /// </summary>
        internal static string Setting_RegisterCornerIcon_Name {
            get {
                return ResourceManager.GetString("Setting_RegisterCornerIcon_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The width of the module..
        /// </summary>
        internal static string Setting_Width_Description {
            get {
                return ResourceManager.GetString("Setting_Width_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string Setting_Width_Name {
            get {
                return ResourceManager.GetString("Setting_Width_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Settings.
        /// </summary>
        internal static string SettingsView_OpenSettings {
            get {
                return ResourceManager.GetString("SettingsView_OpenSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsWindow_Subtitle {
            get {
                return ResourceManager.GetString("SettingsWindow_Subtitle", resourceCulture);
            }
        }
    }
}
